PV179/JobsPortal.PresentationLayer/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.IO.MemoryMappedFiles;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JobsPortal.BusinessLayer.DataTransferObjects;
using JobsPortal.BusinessLayer.DataTransferObjects.Common;
using JobsPortal.BusinessLayer.DataTransferObjects.Filters;
using JobsPortal.BusinessLayer.Facades;
using JobsPortal.PresentationLayer.Models;
using X.PagedList;

namespace JobsPortal.PresentationLayer.Controllers
{
   
    public class CompaniesController : Controller
    {
        public CompanyFacade CompanyFacade { get; set; }

        public const int PageSize = 10;

        private readonly string pageNumberSessionKey = "pageNumber";

        private readonly string filterSessionKey = "filter";

        public JobOfferFacade JobOfferFacade { get; set; }

        public UserFacade UserFacade { get; set; }



        public ActionResult Register()
        {
            return View();
        }

        public ActionResult JobOfferCreated()
        {
            return View();
        }

        [Authorize(Roles = "Company")]
        public async Task<ActionResult> JobOffers(int page = 1)
        {
            Session[pageNumberSessionKey] = page;
            var filter = Session[filterSessionKey] as JobOfferFilterDto ??
                       new JobOfferFilterDto() { PageSize = PageSize };

            filter.RequestedPageNumber = page;
            var comp = await CompanyFacade.GetCompanyAccordingToLoginAsync(User.Identity.Name);
            filter.CompanyId = comp.Id;

            var result = await JobOfferFacade.ListFilteredJobsAsync(filter);
            var model = InitializeJobOfferListViewModel(result);
            return View(model);
        }

        [Authorize(Roles = "Company")]
        [HttpPost]
        public async Task<ActionResult> JobOffers(JobOfferListViewModel model)
        {
            model.Filter.PageSize = PageSize;
            Session[filterSessionKey] = model.Filter;
            var result = await JobOfferFacade.ListFilteredJobsAsync(model.Filter);
            var newModel = InitializeJobOfferListViewModel(result);
            return View(newModel);
        }

        //----------------------------------------------------------------------------------
        [Authorize(Roles = "Company")]
        [HttpPost]
        public async Task<ActionResult> ApplicationsForJobOffer(ApplicationsViewModel model)
        {
            model.Filter.PageSize = PageSize;
            Session[filterSessionKey] = model.Filter;
            var result = await JobOfferFacade.GetAllApplicationsOfJobOffer(model.Filter);
            var newModel = await InitializeApplicationListViewModel(result);
            return View("Applications", newModel);
        }

        [Authorize(Roles = "Company")]
        public async Task<ActionResult> ApplicationsForJobOffer(Guid id, int page = 1)
        {
            Session[pageNumberSessionKey] = page;
            var filter = Session[filterSessionKey] as ApplicationFilterDto ??
                       new ApplicationFilterDto() { PageSize = PageSize };

            filter.RequestedPageNumber = page;
            filter.JobOfferId = id;

            var result = await JobOfferFacade.GetAllApplicationsOfJobOffer(filter);
            var model = await InitializeApplicationListViewModel(result);

            return View("Applications", model);
        }
        //----------------------------------------------------------------------------
        [Authorize(Roles = "Company")]
        public async Task<ActionResult> ApplicationResolve(Guid id)
        {
            var model = new ApplicationResolveModel();
            model.Application = await JobOfferFacade.GetApplicationById(id);
            model.JobOfferDto = await JobOfferFacade.GetJobOfferByIdAsync(model.Application.JobOfferId);
            model.User = await UserFacade.GetUserAccordingToId(model.Application.UserId);
            
            return View("ApplicationResolve", model);
        }

        [Authorize(Roles = "Company")]
        [HttpPost]
        public async Task<ActionResult> ApplicationResolve(ApplicationResolveModel model)
        {

            var url = Request.UrlReferrer.AbsoluteUri;

            var applicationId = Guid.Parse(url.Split('/').Last());
            await CompanyFacade.ChangeApplicationJobOfferState(applicationId, model.Application.JobOfferState);
            return RedirectToAction("ChangesSaved");
        }

        private async Task<ApplicationsViewModel> InitializeApplicationListViewModel(QueryResultDto<ApplicationDto, ApplicationFilterDto> result)
        {
            var model = new ApplicationsViewModel()
            {
                Applications = new StaticPagedList<ApplicationDto>(result.Items, result.RequestedPageNumber ?? 1, PageSize, (int)result.TotalItemsCount),
                Filter = result.Filter
            };
            model.Users = new List<UserDto>();
            for (int i = 0; i < model.Applications.Count; i++)
            {
                var user = await UserFacade.GetUserAccordingToId(model.Applications[i].UserId);
                model.Users.Add(user);
            }

            return model;
        }

        private JobOfferListViewModel InitializeJobOfferListViewModel(QueryResultDto<JobOfferDto, JobOfferFilterDto> result)
        {
            return new JobOfferListViewModel()
            {
                JobOffers = new StaticPagedList<JobOfferDto>(result.Items, result.RequestedPageNumber ?? 1, PageSize, (int)result.TotalItemsCount),
                Filter = result.Filter
            };
        }


        [HttpPost]
        public async Task<ActionResult> Register(CompanyCreateDto companyCreateDto)
        {
            try
            {
                await CompanyFacade.RegisterCompany(companyCreateDto);


                return RedirectToAction("RegistrationDone", "Home");
            }
            catch (ArgumentException)
            {
                ModelState.AddModelError("", "Company with that username already exists!");
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }
       
        [HttpPost]
        public async Task<ActionResult> Login(LoginModel model, string returnUrl)
        {
            (bool success, string roles) = await CompanyFacade.Login(model.Username, model.Password);
            if (success)
            {
                //FormsAuthentication.SetAuthCookie(model.Username, false);

                var authTicket = new FormsAuthenticationTicket(1, model.Username, DateTime.Now,
                    DateTime.Now.AddMinutes(30), false, roles);
                string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                HttpContext.Response.Cookies.Add(authCookie);

                var decodedUrl = "";
                if (!string.IsNullOrEmpty(returnUrl))
                {
                    decodedUrl = Server.UrlDecode(returnUrl);
                }

                if (Url.IsLocalUrl(decodedUrl))
                {
                    return Redirect(decodedUrl);
                }
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Wrong username or password!");
            return View();
        }



        [Authorize(Roles = "Company")]
        public ActionResult CreateJobOffer()
        {
            return View();
        }

        [Authorize(Roles = "Company")]
        [HttpPost]
        public async Task<ActionResult> CreateJobOffer(JobOfferCreateDto jobOfferCreateDto)
        {
            var company = await CompanyFacade.GetCompanyAccordingToLoginAsync(User.Identity.Name);
            jobOfferCreateDto.CompanyId = company.Id;
            await CompanyFacade.CreateJobOffer(jobOfferCreateDto);
            return RedirectToAction("JobOfferCreated");

        }

        public ActionResult ChangesSaved()
        {
            return View();
        }

    }
}

PV179/JobsPortal.PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                   @Html.ActionLink("Jobs Portal", "Index", "JobOffer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav  navbar-right">
                    @{
                        if (Request.IsAuthenticated)
                        { 
                            if (HttpContext.Current.User.IsInRole("User"))
                            {
                                <li class="dropdown pull-right">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user grey"></span> @User.Identity.Name <b class="caret grey"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("My applications", "Index", "Applications")</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Manage", "Index", "User")</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                                    </ul>
                                </li>
                            }
                            else if (HttpContext.Current.User.IsInRole("Company"))
                            {
                                <li class="dropdown pull-right">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user grey"></span> @User.Identity.Name <b class="caret grey"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Job offers", "JobOffers", "Companies")</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("New job offer", "CreateJobOffer", "Companies")</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                                    </ul>
                                </li>
                            }
                            else if (HttpContext.Current.User.IsInRole("Admin"))
                            {
                                <li class="dropdown pull-right">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user grey"></span> @User.Identity.Name <b class="caret grey"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Users", "Users", "Admin")</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Companies", "Companies", "Admin")</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                                    </ul>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="dropdown pull-right">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user grey"></span><b class="caret grey"></b></a>
                                <ul class="dropdown-menu">

                                    <li>@Html.ActionLink("Register company", "Register", "Companies")</li>
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("Log in company", "Login", "Companies")</li>
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("Register user", "Register", "Home")</li>
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("Log in user", "Login", "Home")</li>
                                    <li class="divider"></li>
                                </ul>
                            </li>

                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>